### ISSUE TITLE
想问下大佬 ZenTracer 怎么用

### ISSUE THREAD

**Issue by super-keys** [dqzg12300/fridaUiTools#18]
hlw的那个版本会用. 你这个版本 填入需要hook的类后怎么启动呢? 
我随便填了个类
![image](https://user-images.githubusercontent.com/8650578/165308284-9aaf59a8-606c-458a-89ca-dca264f26fc3.png)

**Comment by super-keys** [comment]
大概猜测到是怎么用了.. 填入信息后关闭窗口. 应该是自动去hook了.   但我想用 spawn模式去启动APP. 提示附加异常

日志
2022-04-26 21:21:07   actionSpawnStart
2022-04-26 21:21:10   附加异常,application is None
![image](https://user-images.githubusercontent.com/8650578/165309604-71b45905-ba3e-45aa-9d29-e21cdfe7855a.png)

**Comment by dqzg12300** [comment]
你可以尝试切换frida版本试一下。14或者15试试看

**Comment by dqzg12300** [comment]
我检查了一下。知道问题了。你spawn的时候应该是选择下拉框里面的提示，下拉框里面是之前附加过的记录数据。由于frida15的特殊是附加应用名称，所以这里记录的直接是应用名，而spawn启动需要传递包名，所以你spawn附加时，直接自己填packageName上去，成功附加一次后，也会写入下面的提示框记录，然后下次你就可以从下拉框选择来方便的附加了。

**Comment by super-keys** [comment]
> 我检查了一下。知道问题了。你spawn的时候应该是选择下拉框里面的提示，下拉框里面是之前附加过的记录数据。由于frida15的特殊是附加应用名称，所以这里记录的直接是应用名，而spawn启动需要传递包名 解决办法是，你spawn附加时，直接自己填packageName上去，就成功附加了，记录也会写入下面的提示框记录，下次你就可以从下拉框选择来方便的附加了。

优秀!! 
的确如此. 填包名即可.  然后我发现ZenTracer 一会行一会不行..不知道怎么回事.

**Comment by dqzg12300** [comment]
不是很清楚了。我是比较简单测试的。可能hook东西较多容易出问题。
