### ISSUE TITLE
win10运行不了。

### ISSUE THREAD

**Issue by linuxxx** [dqzg12300/fridaUiTools#2]
![image](https://user-images.githubusercontent.com/2128377/124101843-591bb300-da92-11eb-9546-4906d6ca9402.png)

python 3.8.8

**Comment by dqzg12300** [comment]
win10可以运行。我的测试环境就是win10。这个问题可能是环境导致的。我另外上传了一个版本fridaUiTools_for_window_test.zip
。这个是带命令行窗口的。你用cmd来启动软件。就能看到什么原因的环境错误。
