### ISSUE TITLE
需要专用14.2.18版本的frida,工具能否切换版本,或者下载老版本是否可以

### ISSUE THREAD

**Issue by wxyzyou** [dqzg12300/fridaUiTools#24]

**Comment by dqzg12300** [comment]
好的。下周有空我优化下自己选版本

**Comment by wxyzyou** [comment]
感谢处理,另外工具再使用时不能灵活的使用本地文件,使用模板哪里的文件,每次修改都要重新复制粘贴到软件再保存本地,及其麻烦

**Comment by wxyzyou** [comment]
实际使用中,重新编辑了custom文件夹的js文件后,程序重新hook并不会更新js,而是注入的最后一次程序保存的js代码
所以才说每次都需要重新赋值粘贴到程序再次保存,hook才会是最新js

**Comment by dqzg12300** [comment]
看了下代码应该不会有这个问题，我传的是文件名，附加前读取文件内容出来填到脚本内容的。我明天测试下。

**Comment by dqzg12300** [comment]
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/19391415/200715415-77197bbe-93d5-4aca-86ce-c8cf8efb9994.png">

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/19391415/200715973-b12202df-59c3-4038-937b-f3dabd72132a.png">

没有发现你说的问题哦。我的测试流程是：修改测试模版内容打印test,然后启动附加，看到打印内容后，终止附加，然后修改成打印test2222，然后重新附加。看上去并没有出现你说的情况。

**Comment by dqzg12300** [comment]
版本切换已添加。可以试试看能用吗

**Comment by wxyzyou** [comment]
我看到发布的是mac版,忘记说了,我使用的是Windows版

**Comment by dqzg12300** [comment]
win的要等两天，win的电脑坏了，送修还没回来。到时候编译了再放上来
