### ISSUE TITLE
frida默认端口被检测

### ISSUE THREAD

**Issue by yuzhiyizhan** [dqzg12300/fridaUiTools#26]
某东检测了frida的默认端口，一附加进程就会闪退，大佬是否能加个配置文件换个端口

**Comment by dqzg12300** [comment]
好的。近期会调整

**Comment by wgetnz** [comment]
> 某东检测了frida的默认端口，一附加进程就会闪退，大佬是否能加个配置文件换个端口

确定是检测端口不是反调试吗？

**Comment by yuzhiyizhan** [comment]
好的，感谢大佬

**Comment by dqzg12300** [comment]
功能已添加，晚点发release
