### ISSUE TITLE
x86用的哪个模拟器？

### ISSUE THREAD

**Issue by taotaoli123** [dqzg12300/fridaUiTools#28]
fridaUiTools_for_window1.0.6版本frida选择的14.2.18，试了“雷电3x/4x-32位”，“逍遥5.1/7.1-32位”，上传frida-server均已失败告终，手动上传并启动，只能获取应用信息，其他功能都无法正常使用。
作者大大测试的是哪款模拟器，系统位数，frida版本等信息，请告知。

**Comment by dqzg12300** [comment]
收到。我测试下雷电模拟器

**Comment by dqzg12300** [comment]
雷电模拟器测试一切正常呀，我测试了上传，启动frida，附加脚本，都没问题。
要先开启一下模拟器的root权限。然后进行操作。如果有问题可以看操作日志里面的提示

**Comment by dqzg12300** [comment]
测试了一下发布版的。确实有点bug。已经修复了。下载1.0.7试试看
