### ISSUE TITLE
win10无法运行

### ISSUE THREAD

**Issue by Weirdo0011** [dqzg12300/fridaUiTools#3]
ImportError: ERROR: fail to load the dynamic library.

**Comment by dqzg12300** [comment]
这是环境缺少了什么库。如果是win的可以在release下载fridaUiTools_for_window_test.zip。然后用命令行打开软件。会提示你缺少了什么

**Comment by dqzg12300** [comment]
我用虚拟机查了下。是少了keystone.dll。我重新上传一份最新release把
