### ISSUE TITLE
hook_RegisterNatives有问题

### ISSUE THREAD

**Issue by kissqy** [dqzg12300/fridaUiTools#31]
![QQ截图20221120175941](https://user-images.githubusercontent.com/86392115/202896027-30f30676-4171-49c4-950d-ce420517b625.png)
![QQ截图20221120180120](https://user-images.githubusercontent.com/86392115/202896031-040174dc-70c8-4827-b041-4b941bf2021a.png)
fridaUiTools软件打印的 少了前面一大截 从0x23才开始打印 自己在vs code里面运行则完整的打印了0x23之前的内容 fridaUiTools软件最开始的版本是完整的 后来的新版都有这个问题 还希望修复一下 软件非常好 希望一直维护

**Comment by dqzg12300** [comment]
好的。明天有空会修复的。谢谢支持。有时间会一直维护和更新的。

**Comment by kissqy** [comment]
> 好的。明天有空会修复的。谢谢支持。有时间会直接维护和更新的。

还有一个问题 如果FCAnd_Jnitrace可以指定so就好了 不然打印出来的数据可以直接把电脑撑爆 相信大部分人也只需要针对个别so 用Jnitrace直接app闪退 用FCAnd_Jnitrace倒是不会 不过数据太多了 不能指定so 真的非常好的 帮助我这种菜鸟 多谢

**Comment by dqzg12300** [comment]
没问题。我调整成可以设置，也可以填空吧

**Comment by dqzg12300** [comment]
已修复和优化jnitrace，晚上会打包win的发上来
