### ISSUE TITLE
frida启动路径名字修改

### ISSUE THREAD

**Issue by wxyzyou** [dqzg12300/fridaUiTools#32]
程序文件夹下的sh/tmp里的 frida_win.bat 内是命令
我尝试修改,发现软件在运行frida时,依旧会重置为原来的命令
我怎么才能手动更改frida文件名和启动路径
另外感谢多版本的兼容

**Comment by dqzg12300** [comment]
修改frida_win.tmp即可。把我替换的占位符直接写成你的就行了

**Comment by wxyzyou** [comment]
感谢,测试成功了,但是使用14版的时候(15没测)  spawn模式,使用自定义的文件 HOOK并没有起效
用界面上的勾选功能倒是起效

**Comment by dqzg12300** [comment]
额。我测试了下。没发现有这种情况。
