### ISSUE TITLE
关于端口转发的问题

### ISSUE THREAD

**Issue by Rungjen** [dqzg12300/fridaUiTools#33]
用wifi连接，启动frida命令中并没有体现出来 (没有替换转发端口27042)
adb shell su 0 /data/local/tmp/frida-server-16.0.2-android-arm64 -l 192.168.0.102:6666
adb forward tcp:27042 tcp:27042
adb forward tcp:27043 tcp:27043

这里的两个端口不应该对应么
希望大佬有时间回答一下。

**Comment by dqzg12300** [comment]
是的。应该对应。我很少使用wifi连接方式，就忘记处理了。明天会优化一下

**Comment by Rungjen** [comment]
谢谢，我已经处理好了
