### ISSUE TITLE
想问一下frida的类型能自定义吗 目前软件支持的貌似只有arm，比如我用模拟器的话如何使用对应的x86版本呢？

### ISSUE THREAD

**Issue by JJymsWorld** [dqzg12300/fridaUiTools#4]
以上 问题。

**Comment by dqzg12300** [comment]
你是指frida-server想要传到模拟器使用么？就是上传和下载那里的上传frida的功能想要包含x86版本的。和执行菜单里面需要多个启动x86版本的把。

**Comment by JJymsWorld** [comment]
> 你是指frida-server想要传到模拟器使用么？就是上传和下载那里的上传frida的功能想要包含x86版本的。和执行菜单里面需要多个启动x86版本的把。

是的 目前会附加进程不成功

**Comment by dqzg12300** [comment]
好的。下一次更新会增加支持

**Comment by JJymsWorld** [comment]
> 好的。下一次更新会增加支持

好的，十分感谢！
