### ISSUE TITLE
PushFridaServerX86 好像没有修改名称 

### ISSUE THREAD

**Issue by zhanghecn** [dqzg12300/fridaUiTools#44]
好像 PushFridaServerX86  和 PushFridaServer 代码有点差异  导致 启动 x86 frida 失败了

大佬 您的是 Pyinstaller -w -D .\kmainForm.py 这个命令打包的么 
我打包的好像 有点问题

**Comment by zhanghecn** [comment]
刚刚看到了 kmainForm.spec.bak

**Comment by dqzg12300** [comment]
PushFridaServerX86最新代码已经优化。打包有什么错误吗？
