### ISSUE TITLE
无法连接模拟器

### ISSUE THREAD

**Issue by Weirdo0011** [dqzg12300/fridaUiTools#5]
可以出一份教程吗

**Comment by dqzg12300** [comment]
模拟器点上传模拟器的frida-server。然后启动frida-server再连接。过段时间我搞个简单的教程把

**Comment by dqzg12300** [comment]
添加了个简单例子。在readme中查看

**Comment by elvishoo** [comment]
模拟器应该大部分是remote模式连接，但是工具貌似是usb所以导致device not found.
最新的1.0.2包里我这边下载到的还是14.2.18的frida-server，是上传错了吗？
