### ISSUE TITLE
无法连接模拟器的原因

### ISSUE THREAD

**Issue by elvishoo** [dqzg12300/fridaUiTools#7]
模拟器应该大部分是remote模式连接，但是工具貌似是usb所以导致device not found.
最新的1.0.2包里我这边下载到的还是14.2.18的frida-server，是上传错了吗？

**Comment by dqzg12300** [comment]
额。我本地用15.1的发现有些细节有bug。就调成14.2的版本在使用。我例子里面也是直接使用的模拟器。可以连接上的。

**Comment by dqzg12300** [comment]
找不到设备也可能是和你本地的frida版本有关系。你看看是哪个版本的frida

**Comment by elvishoo** [comment]
我本地和模拟器都是15.1.8，逍遥模拟器，在cmd下用fridaps -U 和frida-dexdump都没问题 ，但是用工具就连不上，显示device not found

**Comment by dqzg12300** [comment]
好的。我晚点测试一下这个模拟器

**Comment by elvishoo** [comment]
刚才在kali里连了一下，显示没连上，回头再看，又连上了，我现在很懵，不知道啥原因。。。

**Comment by dqzg12300** [comment]
win linux mac我都测试过可以正常连接来着的。要是连接不上。你关掉软件重新打开试试看

**Comment by elvishoo** [comment]
反复打开几次之后，就正常了，很奇怪。但算是解决了吧。。

**Comment by dqzg12300** [comment]
好像我也碰到过。后来反复测试没有重现出来。就没管了
