### ISSUE TITLE
显示上传完成，但是文件内没有

### ISSUE THREAD

**Issue by Weirdo0011** [dqzg12300/fridaUiTools#8]
显示上传完成，但是文件内没有，启动frida闪退

**Comment by dqzg12300** [comment]
两种情况，一个是手机还没连接上，另一种是cmd的su权限方式不一样。
菜单那里有个切换cmd，点一下切换su 0的。前面的版本忘记加判断返回了。你切换了试试看。最新的版本已经加返回结果判断了。

**Comment by dqzg12300** [comment]
具体上传失败原因可以看操作日志。里面会将命令执行的结果打印出来

**Comment by Weirdo0011** [comment]
上传的时候文件名需要用hluda-server-14.2.18-android-arm，启动的frida-server-14.2.18-android-arm

**Comment by Weirdo0011** [comment]
可以增加上传frida文件选项吗？比如x86 x64  arm 选项，还有连接方式增加remote或usb选项

**Comment by Weirdo0011** [comment]
![QQ截图20211105115222](https://user-images.githubusercontent.com/87079338/140455479-d8eea08c-3da6-4bb7-990d-6f385f85f295.png)
上传成功。启动也成功，frida-ps -u也能查到进程的，但是软件会显示未连接

**Comment by dqzg12300** [comment]
hluda-server是去掉了一些frida特征的所以我直接用这个替换的。你是说想单个上传。用哪个就传哪个么？我觉得可以分成两个按钮。一个是上传真机frida-server。一个是传模拟器frida-server就好了。连接方式增加remote这个可以。回头有空我加一下。

**Comment by dqzg12300** [comment]
后面的新版本我优化了上传失败的提示。不会只要命令执行成功就当成功了。

**Comment by Weirdo0011** [comment]
好的，感谢
